const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(languages);
var declareFirstElement = 'The first element of the array is';
var firstElement = languages[0];
console.log(declareFirstElement, firstElement);
var declareThirdElement = 'The 3rd element of the array is';
var thirdElement = languages[2];
console.log(declareThirdElement, thirdElement);
var declareLength = 'The length of the array is';
var length = languages.length;
console.log(declareLength, length);
var declareLastElement = 'The last element of the array is';
var lastElement = languages[languages.length - 1];
console.log(declareLastElement, lastElement);
